Translate v6.7.0 post
nodejs/nodejs-ko pull request #433
Opened 2016-09-29 02:40 UTC by marocchino

close #429 

review please. @nodejs/nodejs-ko

2016-09-29 02:42 UTC, marocchino commented on source/_posts/2016-09-28-release-v6.7.0.md
> +**중요한 보안 릴리스입니다**. 모든 Node.js 사용자는 수정된 취약점에 대한 자세한 내용을 [보안 릴리스 요약](https://nodejs.org/en/blog/vulnerability/september-2016-security-releases)에서 확인하세요.
#426 이 끝난후에 수정이 필요합니다.

2016-09-29 02:43 UTC, marocchino commented
특히 내용이 겹치는 @lucykang 님이 확인해 주셨으면 합니다.

2016-09-29 02:46 UTC, lucykang commented
네. 알겠습니다. 제꺼 끝내고 확인해보겠습니다

2016-09-30 02:31 UTC, yous commented on source/_posts/2016-09-28-release-v6.7.0.md
> +### 주요변경사항
주요변경사항 → 주요 변경사항

2016-09-30 02:31 UTC, yous commented on source/_posts/2016-09-28-release-v6.7.0.md
> +  - 1.0.2j로 업그레이드, 1.0.2i에 포함된 CRLs을 사용할 때 충돌하는 결함(CVE-2016-7052)을 수정했습니다.(Shigeki Ohtsu) [#8786](https://github.com/nodejs/node/pull/8786)
CRLs을 → CRL을

복수형인 것 같습니다.

2016-09-30 02:31 UTC, yous commented on source/_posts/2016-09-28-release-v6.7.0.md
> +* **buffer**: Zero-fill excess bytes in `Buffer.concat()`으로 생성된 새 `Buffer` 객체에 원본 `Buffer` 객체의 총 길이를 초과하는 `totalLength` 파라미터를 넘길 때 초과된 바이트에 0를 채워넣습니다.(Сковорода Никита Андрееви��) [nodejs/node-privat
'Zero-fill excess bytes in'을 지워주세요.

2016-09-30 02:31 UTC, yous commented on source/_posts/2016-09-28-release-v6.7.0.md
> +* **tls**: CVE-2016-7099 - 올바르지 않은 와일드카드 인증 검증을 수정했습니다. TLS 서버가 자신의 호스트 이름에 대해 적절하지 않은 와일드카드 검증 `*.`때문에 올바르지 않은 와일드 카드 인증을 할 수 있었습니다. Alexander Minozhenko, James Bunton(Atlassian)에 의해 처음 보고되었습니다.(Ben
> 적절하지 않은 와일드카드 검증 \`\*.\`때문에

'적절하지 않은 \`\*.\` 와일드카드 검증 때문에'는 어떻습니까?

2016-09-30 05:23 UTC, marocchino commented on source/_posts/2016-09-28-release-v6.7.0.md
> +* **tls**: CVE-2016-7099 - 올바르지 않은 와일드카드 인증 검증을 수정했습니다. TLS 서버가 자신의 호스트 이름에 대해 적절하지 않은 와일드카드 검증 `*.`때문에 올바르지 않은 와일드 카드 인증을 할 수 있었습니다. Alexander Minozhenko, James Bunton(Atlassian)에 의해 처음 보고되었습니다.(Ben
좋습니다. 75ce393에서 수정했습니다.

2016-09-30 05:23 UTC, marocchino commented on source/_posts/2016-09-28-release-v6.7.0.md
> +* **buffer**: Zero-fill excess bytes in `Buffer.concat()`으로 생성된 새 `Buffer` 객체에 원본 `Buffer` 객체의 총 길이를 초과하는 `totalLength` 파라미터를 넘길 때 초과된 바이트에 0를 채워넣습니다.(Сковорода Никита Андрееви��) [nodejs/node-privat
75ce393에서 수정했습니다.

2016-09-30 05:23 UTC, marocchino commented on source/_posts/2016-09-28-release-v6.7.0.md
> +  - 1.0.2j로 업그레이드, 1.0.2i에 포함된 CRLs을 사용할 때 충돌하는 결함(CVE-2016-7052)을 수정했습니다.(Shigeki Ohtsu) [#8786](https://github.com/nodejs/node/pull/8786)
75ce393에서 수정했습니다.

2016-09-30 05:24 UTC, marocchino commented on source/_posts/2016-09-28-release-v6.7.0.md
> +### 주요변경사항
75ce393에서 수정했습니다.

2016-09-30 06:00 UTC, outsideris requested changes

2016-09-30 06:00 UTC, outsideris commented on source/_posts/2016-09-28-release-v6.7.0.md
> +Semver 부:
`Semver 부 버전`라고 쓰는건 어떤가요?

2016-09-30 06:00 UTC, outsideris commented on source/_posts/2016-09-28-release-v6.7.0.md
> +  - 동적 서드파티 엔진 모듈 지원을 제거했습니다. 공격자가 Node.js 런타임에 동적 엔진 모듈로 가장하여 악의적인 코드를 숨길 있습니다. Ahmed Zaki(Skype)가 처음 보고했습니다.(Ben Noordhuis) [nodejs/node-private#73](https://github.com/nodejs/node-private/pull/73)
`코드를 숨길 있습니다.`에 `숨길 수`의 수가 빠졌습니다.

2016-09-30 06:00 UTC, outsideris commented on source/_posts/2016-09-28-release-v6.7.0.md
> +* **buffer**: `Buffer.concat()`으로 생성된 새 `Buffer` 객체에 원본 `Buffer` 객체의 총 길이를 초과하는 `totalLength` 파라미터를 넘길 때 초과된 바이트에 0를 채워넣습니다.(Сковорода Никита Андрееви��) [nodejs/node-private#64](https://github.com/n
원문 복사부터 그런것 같은데 `Сковорода Никита Андрееви��`이름에 이상한 기호가 들어갔습니다. `Сковорода Никита Андреевич`로 바뀌어야 해요.

2016-09-30 06:00 UTC, outsideris commented on source/_posts/2016-09-28-release-v6.7.0.md
> +* **src**: crypto.pbkdf2()에 빈 패스워드나 솔트를 넘겨 치명적인 오류를 일으킬 수 있는 회귀 수정(Rich Trott) [#8572](https://github.com/nodejs/node/pull/8572)
다른 문구랑 비교하면 `회귀를 수정했습니다.`로 문자으로 쓰는게 좋아보입니다.

2016-09-30 06:00 UTC, outsideris commented on source/_posts/2016-09-28-release-v6.7.0.md
> +* **v8**: 얼려진 객체에 정규표현을 사용할 때 충돌이 일어나는 회귀 수정(Myles Borins) [#8673](https://github.com/nodejs/node/pull/8673)
여기도요.

2016-09-30 06:01 UTC, outsideris commented
리뷰기능 처음 써봐서 한번 `changes reqeust`를 눌러봤습니다. ㅡㅡ;; 보시고 적용하실꺼만 하시면 됩니다. ㅎㅎㅎ

2016-09-30 23:09 UTC, marocchino commented on source/_posts/2016-09-28-release-v6.7.0.md
> +* **v8**: 얼려진 객체에 정규표현을 사용할 때 충돌이 일어나는 회귀 수정(Myles Borins) [#8673](https://github.com/nodejs/node/pull/8673)
04bb541 에서 전부 적용했습니다.

2016-09-30 23:30 UTC, marocchino commented
다 수정한거 같은데 `Changes requested`가 사라지지 않네요. 이거 리뷰어 확인이 필요한 건가요? -3-

2016-10-01 10:35 UTC, outsideris approved these changes

2016-10-01 10:36 UTC, outsideris commented
제가 approved를 눌러야 하네요 ㅎ

2016-10-04 23:37 UTC, marocchino commented
어느정도 리뷰 끝난것 같으니 #435  머지되면 링크 수정하고 머지하겠습니다.

2016-10-05 05:48 UTC, outsideris commented
넵

2016-10-06 01:33 UTC, merged

2016-10-06 01:50 UTC, yous commented on source/_posts/2016-09-28-release-v6.7.0.md
> +**중요한 보안 릴리스입니다**. 모든 Node.js 사용자는 수정된 취약점에 대한 자세한 내용을 [보안 릴리스 요약](http://nodejs.github.io/nodejs-ko/articles/2016/09/25/security-updates-for-all-active-release-lines-september-2016/)에서 확인하세요.
기본적으로 *.github.io 링크에 HTTPS를 사용할 수 있습니다. 😀

2016-10-06 02:17 UTC, marocchino commented on source/_posts/2016-09-28-release-v6.7.0.md
> +**중요한 보안 릴리스입니다**. 모든 Node.js 사용자는 수정된 취약점에 대한 자세한 내용을 [보안 릴리스 요약](http://nodejs.github.io/nodejs-ko/articles/2016/09/25/security-updates-for-all-active-release-lines-september-2016/)에서 확인하세요.
다음 PR에서 수정하겠습니다!