Translates security release news
nodejs/nodejs-ko pull request #438
Opened 2016-10-06 02:18 UTC by marocchino

close #432, #431 and #430

2016-10-07 05:07 UTC, outsideris requested changes

2016-10-07 05:07 UTC, outsideris commented on source/_posts/2016-09-28-release-v0.10.47.md
> +title: Node v0.10.47 (유지보수)
괄호 앞에 공백 빼주세요.

2016-10-07 05:07 UTC, outsideris commented on source/_posts/2016-09-28-release-v0.10.47.md
> +* openssl: 1.0.1u로 업그레이드, Node.js에 영향을 주는 몇몇 결함 CVE-2016-6304("OCSP 상태 요청이 무한 메모리 증가로 확장, 높은 우선순위), CVE-2016-2183, CVE-2016-6303, CVE-2016-2178, CVE-2016-6306을 수정했습니다.
severity는 우선순위보다는 심각도로 그동안 번역했습니다.

2016-10-07 05:07 UTC, outsideris commented on source/_posts/2016-09-28-release-v0.10.47.md
> +* tls: CVE-2016-7099 - 올바르지 않은 와일드카드 인증 검증을 수정했습니다. TLS 서버가 자신의 호스트 이름에 대해 적절하지 않은 `*.` 와일드카드 검증 때문에 올바르지 않은 와일드 카드 인증을 할 수 있었습니다. Alexander Minozhenko, James Bunton(Atlassian)에 의해 처음 보고되었습니다.(Ben No
`에 의해 보고되었습니다.` 보다는 `~가 처음 보고했습니다.`가 낫지 않을까요?

2016-10-07 05:07 UTC, outsideris commented on source/_posts/2016-09-28-release-v0.12.16.md
> +  - 1.0.1u로 업그레이드, Node.js에 영향을 주는 몇몇 결함 CVE-2016-6304("OCSP 상태 요청이 무한 메모리 증가로 확장, 높은 우선순위), CVE-2016-2183, CVE-2016-6303, CVE-2016-2178, CVE-2016-6306을 수정했습니다.
여기도 우선순위에 대해서 위에 얘기한 것도 동일합니다.

2016-10-08 10:00 UTC, outsideris approved these changes

2016-10-10 15:36 UTC, yous reviewed
Node v0.10.47의 리뷰는 Node v0.12.16에도 동일하게 적용됩니다.

2016-10-10 15:36 UTC, yous commented on source/_posts/2016-09-28-release-v0.10.47.md
> +title: Node v0.10.47(유지보수)
보통 '유지보수 버전'이라고 했나요?

2016-10-10 15:36 UTC, yous commented on source/_posts/2016-09-28-release-v0.10.47.md
> +  - 이제 부적절한 상태 코드를 보낼 수 없습니다. 100 - 999 사이의 3자리 수로 제한됩니다. 적절한 검증이 없으면 응답 분절 공격을 받을 가능성이 있습니다. v4.x에서 백포트 했습니다. (Brian White)
- '100 - 999'는 '100~999'로 고쳐도 되지 않을까요?
- 윗줄의 '응답 분리 공격'과 이 줄의 '응답 분절 공격' 중 하나로 통일하면 좋을 것 같습니다.
- 이 줄에만 '(Brian White)' 앞에 공백이 있습니다. 통일만 되면 공백이 있는 쪽이든 없는 쪽이든 좋습니다.

2016-10-10 15:36 UTC, yous commented on source/_posts/2016-09-28-release-v0.10.47.md
> +* openssl: 1.0.1u로 업그레이드, Node.js에 영향을 주는 몇몇 결함 CVE-2016-6304("OCSP 상태 요청이 무한 메모리 증가로 확장, 높은 심각도), CVE-2016-2183, CVE-2016-6303, CVE-2016-2178, CVE-2016-6306을 수정했습니다.
- "OCSP 상태 요청이 ... 확장 → "OCSP 상태 요청이 ... 확장"
- 원문에 'CVE-2016-2183'이 두 번 나오는데 원문 쪽이 잘못된 건가요?

2016-10-10 15:36 UTC, yous commented on source/_posts/2016-09-28-release-v4.6.0.md
> +  - 1.0.2i로 업그레이드, Node.js에 영향을 주는 몇몇 결함 CVE-2016-6304("OCSP 상태 요청이 무한 메모리 증가로 확장, 높은 심각도), CVE-2016-2183, CVE-2016-2178, CVE-2016-6306을 수정했습니다.(Shigeki Ohtsu) [#8714](https://github.com/nodejs/node/
- "OCSP 상태 요청이 ... 확장 → "OCSP 상태 요청이 ... 확장"
- CVE-2016-6303이 빠진 것 같습니다.

2016-10-10 23:43 UTC, marocchino commented on source/_posts/2016-09-28-release-v0.10.47.md
> +* openssl: 1.0.1u로 업그레이드, Node.js에 영향을 주는 몇몇 결함 CVE-2016-6304("OCSP 상태 요청이 무한 메모리 증가로 확장, 높은 심각도), CVE-2016-2183, CVE-2016-6303, CVE-2016-2178, CVE-2016-6306을 수정했습니다.
https://nodejs.org/en/blog/release/v0.10.47/
네 아직도 그런것 같네요.

2016-10-10 23:47 UTC, merged