#498 translate
nodejs/nodejs-ko pull request #536
Opened 2017-03-21 15:13 UTC by pineoc

#498에 있는 문서 번역했습니다.
중간에 Todd moore가 이야기한 부분의 번역이 매끄럽지 않은데 조언 부탁드립니다!

2017-03-25 09:45 UTC, outsideris requested changes

2017-03-25 09:45 UTC, outsideris commented on source/_posts/2017-01-20-community-2017-election.md
> +Node.js 재단에는 두 명의 개별 이사가 있으며, 그들은 2년의 임기를 가집니다.
여기서 individual director는 개인자격의 회원을 뜻하는 것 같습니다. 
제목에서는 `개인 회원 이사`로 번역하셨는데 여기는 좀 다르게 번역되었습니다. 제목처럼 `개인 회원 이사`라고 하면 어떨까 싶습니다. 

`Node.js 재단 개별 이사는 Node.js 프로젝트 커뮤니티의 목소리입니다.` -> Node.js 재단의 개인 회원 이사는 Node.js 프로젝트 커뮤니티의 목소리를 이사회에 전달하는 역할을 합니다

정도로 풀어쓰면 어떨까 합니다.

2017-03-25 09:45 UTC, outsideris commented on source/_posts/2017-01-20-community-2017-election.md
> +그리고 연설 참여 시 이사회를 대표하는 것이 포함됩니다.(이는 포괄적인 목록이 아닙니다) 더 자세히 알아보려면 ["What’s it like being on the Node.js Foundation Board of Directors?"](https://medium.com/@nodejs/whats-it-like-being-on-the-node-js-foun
`그리고`는 영어식이라 빠져도 될것 같습니다. 

더 자세히 알라보려면  뒤에 []`를 읽어보세요.`가 추가되어야 할 것 같습니다.

2017-03-25 09:45 UTC, outsideris commented on source/_posts/2017-01-20-community-2017-election.md
> +현재 이사회 멤버가 [여기](https://nodejs.org/en/foundation/board)에 나열되어 있습니다.
이사회 멤버가 -> 이사회 멤버는

2017-03-25 09:45 UTC, outsideris commented on source/_posts/2017-01-20-community-2017-election.md
> +할인 코드는 [contact us](mailto : membership@nodejs.org)로 문의해주십시오.
그냥 `할인 코드는 [저희에게 문의]() 해 주십시오`로 풀어도 될거같습니다.

2017-03-25 15:10 UTC, pineoc commented
@outsideris 님께서 말씀해주신부분 수정했습니다!

2017-03-25 17:31 UTC, outsideris approved these changes

2017-03-27 03:15 UTC, yous commented on source/_posts/2017-01-20-community-2017-election.md
> +이것은 커뮤니티에 이사회의 목소리를 제공하고 우리가 투자 결정을 내리는 방법을 안내하는 데 도움이 됩니다.
'이것은 커뮤니티에 이사회의 목소리를 제공하고' 부분은 '이사회에 커뮤니티가 목소리를 낼 수 있도록 하고' 정도의 의미로 해석했는데 어떠신가요?

2017-03-27 03:15 UTC, yous commented on source/_posts/2017-01-20-community-2017-election.md
> +개별 게시판 회원은 제안된 게시판 항목이 커뮤니티에 미치는 영향에 대한 피드백을 제공할 수 있으며
'board'는 게시판 대신 이사회 정도로 번역되어야 할 것 같습니다.

2017-03-27 03:15 UTC, yous commented on source/_posts/2017-01-20-community-2017-election.md
> +그들은 지역 사회를 가장 잘 대표할 수 있는 정보를 토대로 결정을 내릴 의무를 맡았습니다.
여기서 community는 그냥 커뮤니티로 번역해도 될 것 같습니다.

2017-03-27 03:15 UTC, yous commented on source/_posts/2017-01-20-community-2017-election.md
> +이러한 지식과 피드백을 통해 이사회는 지역 사회가 건강을 유지하고 계속 성장할 수 있는 자원을 제공할 수 있습니다.”
여기서 community는 그냥 커뮤니티로 번역해도 될 것 같습니다.

2017-03-27 03:15 UTC, yous commented on source/_posts/2017-01-20-community-2017-election.md
> +여기에는 이사회 회의에 참여하고 투표하는 것, Node.js 프로젝트의 임무를 포착하는 결론을 내리는 선도적인 노력을 소개하는 것,
> Node.js 프로젝트의 임무를 포착하는 결론을 내리는 선도적인 노력을 소개하는 것

'Node.js 프로젝트의 임무 달성을 위한 계획을 세우고 주도하는 것'은 어떻습니까?

2017-03-27 03:15 UTC, yous commented on source/_posts/2017-01-20-community-2017-election.md
> +- 선거는 **1월 30일 17:00 UTC** 에 끝납니다.
\*\*1월 30일 17:00 UTC\*\* 에 → \*\*1월 30일 17:00 UTC\*\*에

2017-03-27 03:15 UTC, yous commented on source/_posts/2017-01-20-community-2017-election.md
> +연간 회원 비용 [연 100$, 또는 학생용 25$](https://identity.linuxfoundation.org/pid/99).
연간 회원 비용 \[연 100$, 또는 학생용 25$\](...). → 연간 회원 비용은 \[연 100$, 학생은 25$\](...)입니다.

2017-03-27 03:15 UTC, yous commented on source/_posts/2017-01-20-community-2017-election.md
> +할인 코드는 [저희에게 문의](mailto : membership@nodejs.org) 해 주십시오.
`mailto : membership@nodejs.org` → `mailto:membership@nodejs.org`

`mailto:`는 메일 링크 형식입니다.

2017-03-27 03:15 UTC, yous commented on source/_posts/2017-01-20-community-2017-election.md
> +- 위에서 언급한 두 명의 선출된 개별 회원 이사를 통해 Node.js 재단 이사회에서 투표와 목소리를 낼 수 있습니다.
투표와 목소리를 낼 수 있습니다 → 투표를 하거나 목소리를 낼 수 있습니다

2017-03-27 03:15 UTC, yous commented on source/_posts/2017-01-20-community-2017-election.md
> +- Node Interactive 2017를 정기 가격의 20% 할인됩니다.
Node Interactive 2017 정가의 20%를 할인해줍니다.

2017-03-27 04:38 UTC, pineoc commented on source/_posts/2017-01-20-community-2017-election.md
> +이것은 커뮤니티에 이사회의 목소리를 제공하고 우리가 투자 결정을 내리는 방법을 안내하는 데 도움이 됩니다.
이부분의 해석이 신경쓰였는데 그렇게 해석하는게 맞는 것 같습니다.
감사합니다!

2017-03-27 04:42 UTC, pineoc commented on source/_posts/2017-01-20-community-2017-election.md
> +연간 회원 비용 [연 100$, 또는 학생용 25$](https://identity.linuxfoundation.org/pid/99).
입니다 추가할 때, 
연간 회원 비용은 [연 100$, 학생은 25$](...) 입니다. 이렇게 띄고 해야할 것 같은데 어떠신가요?

2017-03-27 04:45 UTC, pineoc commented on source/_posts/2017-01-20-community-2017-election.md
> +연간 회원 비용 [연 100$, 또는 학생용 25$](https://identity.linuxfoundation.org/pid/99).
다음 맞춤법 검사기에서는 붙여서 쓰는게 맞다고 하네요. 붙여서 수정하겠습니다.

2017-03-27 04:51 UTC, pineoc commented
@yous 님이 리뷰해주신 부분 수정했습니다!

2017-03-27 05:03 UTC, yous approved these changes

2017-03-27 14:59 UTC, merged

2017-03-28 03:25 UTC, outsideris commented
아~ squash 머지를 하기로 했는데 제가 모르고 그냥 머지했네요. 다음부터는 주의하겠습니다.