Translate Node v7.7.4
nodejs/nodejs-ko pull request #538
Opened 2017-03-27 12:28 UTC by originerd

Resolves #537.

2017-03-28 00:10 UTC, marocchino approved these changes

2017-03-28 00:10 UTC, marocchino commented on source/_posts/2017-03-21-release-v7.7.4.md
> +* **deps**: 몇 가지 수정이 포함 된, 내부 node-inspect 버전을 1.10.6으로 업그레이드했습니다. (Jan Krems) [#11869](https://github.com/nodejs/node/pull/11869)
어순을 거꾸로해보면 어떨까요?
~~~했습니다. 여기에는 여러 수정이 포함됩니다.

2017-03-28 03:22 UTC, outsideris requested changes

2017-03-28 03:22 UTC, outsideris commented on source/_posts/2017-03-21-release-v7.7.4.md
> +* **tls**: 부분을 읽은 후 핸들이 소멸할 때 세그멘테이션 오류를 수정하였습니다. (Ben Noordhuis) [#11898](https://github.com/nodejs/node/pull/11898)
`일부분만 읽은 후 핸들을 제거할 때 발생하는 세그멘테이션 오류를 수정하였습니다.`는 어떨까요?

2017-03-28 03:22 UTC, outsideris commented on source/_posts/2017-03-21-release-v7.7.4.md
> +title: Node v7.7.4 (현재 버전)
괄호앞의 공백 제거해 주세요.

2017-03-30 05:21 UTC, marocchino commented
@outsideris ping!

2017-03-30 06:45 UTC, yous commented on source/_posts/2017-03-21-release-v7.7.4.md
> +이 릴리즈의 대부분을 준비해주신 @italoacasa 님께 감사드립니다.
`@italoacasa` → `@italoacasas`

2017-03-30 06:45 UTC, yous commented on source/_posts/2017-03-21-release-v7.7.4.md
> +* **inspector**: 0.0.0.0로 연결할 때 적절한 WebSocket URL을 사용합니다. (Eugene Ostroukhov) [#11850](https://github.com/nodejs/node/pull/11850)
0.0.0.0로 → 0.0.0.0으로

2017-04-01 13:28 UTC, outsideris approved these changes

2017-04-01 13:28 UTC, outsideris commented
늦어서 죄송합니다. 머지하겠습니다.

2017-04-01 13:29 UTC, merged