Translate Node v7.8.0 (Current)
nodejs/nodejs-ko pull request #559
Opened 2017-05-19 14:45 UTC by taggon

Resolve #542

2017-05-20 11:59 UTC, outsideris requested changes

2017-05-20 11:59 UTC, outsideris commented on source/_posts/2017-03-29-release-v7.8.0.md
> +  - do not segfault on out-of-range index (Timothy Gu) [#11927](https://github.com/nodejs/node/pull/11927)
이 부분이 번역되지 않았는데 PR을 보면 `인덱스의 범위를 벗어났을때 segfault가 발생하지 않습니다.` 정도가 어떨까요?

2017-05-20 19:01 UTC, outsideris approved these changes

2017-06-01 01:55 UTC, asbubam approved these changes
다봤습니다!

2017-06-01 01:58 UTC, merged