Release v8.1.4, v7.10.1, v6.11.1, v4.8.4
nodejs/nodejs-ko pull request #590
Opened 2017-07-13 14:20 UTC by eunsucking

This closes #587, closes #586, closes #584,  closes #583
중복되는 내용이라 한번에 정리했습니다.

2017-07-14 13:18 UTC, freenice12 commented on source/_posts/2017-07-13-release-v4.8.4.md
> +  - V8 스냅샷 비활성화 - 스냅샷에 포함된 해시시드는 현재 실행되는 모든 바이너리와 같습니다. 이것은 노드가 서비스 거부(Denial of Service)를 일으킬 수 있는 충돌 공격들에 대해 노출된다는 것을 의미합니다. 그래서 우리는 확실한 해결책이 발견될때까지 스냅샷을 비활성화 시킬것입니다. (Ali Ijaz Sheikh)
해시시드는 -> 해시 시드는,
발견될때까지 -> 발견될 때까지,
시킬것입니다. -> 시킬 것입니다.

2017-07-14 13:19 UTC, freenice12 commented on source/_posts/2017-07-13-release-v7.10.1.md
> +  - V8 스냅샷 비활성화 - 스냅샷에 포함된 해시시드는 현재 실행되는 모든 바이너리와 같습니다. 이것은 노드가 서비스 거부(Denial of Service)를 일으킬 수 있는 충돌 공격들에 대해 노출된다는 것을 의미합니다. 그래서 우리는 확실한 해결책이 발견될때까지 스냅샷을 비활성화 시킬것입니다. (Ali Ijaz Sheikh)
해시시드는 -> 해시 시드는,
발견될때까지 -> 발견될 때까지,
시킬것입니다. -> 시킬 것입니다.

2017-07-14 13:19 UTC, freenice12 commented on source/_posts/2017-07-13-release-v8.1.4.md
> +  - V8 스냅샷 비활성화 - 스냅샷에 포함된 해시시드는 현재 실행되는 모든 바이너리와 같습니다. 이것은 노드가 서비스 거부(Denial of Service)를 일으킬 수 있는 충돌 공격들에 대해 노출된다는 것을 의미합니다. 그래서 우리는 확실한 해결책이 발견될때까지 스냅샷을 비활성화 시킬것입니다. (Ali Ijaz Sheikh)
해시시드는 -> 해시 시드는,
발견될때까지 -> 발견될 때까지,
시킬것입니다. -> 시킬 것입니다.

2017-07-16 08:04 UTC, eunsucking commented
@freenice12 리뷰 감사합니다. 수정하였습니다.

2017-07-16 12:12 UTC, MJayJang requested changes

2017-07-16 12:12 UTC, MJayJang commented on source/_posts/2017-07-13-release-v4.8.4.md
> +  - CVE-2017-1000381 - NAPTR 응답을 분석하는데 사용되는 c-ares 함수 `ares_parse_naptr_reply()`는, 전달된 DNS 응답 패킷이 특정 방식으로 만들어진 경우, 주어진 입력 버퍼의 외부 메모리를 읽을 수 있도록 트리거 될 수 있습니다. 이 패치는 레코드를 처리하기 전에 NAPTR 레코드의 필수 요소 (int16
1. 분석하는데 -> 분석하는 데
2. 필수 요소 (int16의경우 -> 필수 요소(int16의 경우

2017-07-16 12:41 UTC, yous commented on source/_posts/2017-07-13-release-v4.8.4.md
> +  - CVE-2017-1000381 - NAPTR 응답을 분석하는데 사용되는 c-ares 함수 `ares_parse_naptr_reply()`는, 전달된 DNS 응답 패킷이 특정 방식으로 만들어진 경우, 주어진 입력 버퍼의 외부 메모리를 읽을 수 있도록 트리거 될 수 있습니다. 이 패치는 레코드를 처리하기 전에 NAPTR 레코드의 필수 요소 (int16
int16의경우 → int16의 경우

2017-07-16 12:42 UTC, yous commented on source/_posts/2017-07-13-release-v4.8.4.md
> +  - CVE-2017-1000381 - NAPTR 응답을 분석하는데 사용되는 c-ares 함수 `ares_parse_naptr_reply()`는, 전달된 DNS 응답 패킷이 특정 방식으로 만들어진 경우, 주어진 입력 버퍼의 외부 메모리를 읽을 수 있도록 트리거 될 수 있습니다. 이 패치는 레코드를 처리하기 전에 NAPTR 레코드의 필수 요소 (int16
이미 언급된 사항이었네요. 그러면 된 것 같습니다.

2017-07-19 10:59 UTC, eunsucking commented
@MJayJang @yous 리뷰 감사합니다. 수정하였습니다.

2017-07-19 11:08 UTC, yous approved these changes

2017-07-20 07:03 UTC, MJayJang approved these changes

2017-07-21 03:43 UTC, outsideris commented
두분 승인하셨으므로 머지합니다.

2017-07-21 03:43 UTC, merged