#631
nodejs/nodejs-ko pull request #632
Opened 2017-11-04 17:06 UTC by BaroqueCoding

git은 아직 초보입니다. 일단 가이드를 따라해보고 있습니다만 제대로 하고 있는지 모르겠네요
잘 부탁드립니다.

2017-11-05 09:25 UTC, outsideris commented
#631 
다음에 작업하실 때는 다른 분과 작업이 겹칠수 있으니 작업 시작 전에 이슈에 댓글을 남겨주시면 좋습니다.

2017-11-05 09:30 UTC, outsideris commented on source/_posts/2017-10-31-release-v9.0.0.md
> +title: Node v9.0.0 (현재 버전)
괄호앞에 공백을 제거해 주세요.

2017-11-05 09:30 UTC, outsideris commented on source/_posts/2017-10-31-release-v9.0.0.md
> +  * 에러들은 프로세스의 nextTick에 발생합니다. [[`f2b01cba7b`](https://github.com/nodejs/node/commit/f2b01cba7b)] [#4670](https://github.com/nodejs/node/pull/4670)
`프로세스의 nextTick에서 오류 이벤트를 발생시킵니다.`는 어떨까요?

2017-11-05 09:35 UTC, BaroqueCoding commented on source/_posts/2017-10-31-release-v9.0.0.md
> +title: Node v9.0.0 (현재 버전)
수정하겠습니다.

2017-11-05 09:36 UTC, BaroqueCoding commented on source/_posts/2017-10-31-release-v9.0.0.md
> +  * 에러들은 프로세스의 nextTick에 발생합니다. [[`f2b01cba7b`](https://github.com/nodejs/node/commit/f2b01cba7b)] [#4670](https://github.com/nodejs/node/pull/4670)
그쪽이 더 자연스러워보이네요.

2017-11-05 09:39 UTC, BaroqueCoding commented
다음에는 작업전에 댓글 남기도록 하겠습니다.

2017-11-05 14:24 UTC, eunsucking requested changes

2017-11-05 14:24 UTC, eunsucking commented on source/_posts/2017-10-31-release-v9.0.0.md
> +  * 소켓 커넥션이 일어났을때 타임아웃이 설정됩니다. [[`10be20a0e8`](https://github.com/nodejs/node/commit/10be20a0e8)] [#8895](https://github.com/nodejs/node/pull/8895)
일어났을 때

2017-11-05 14:24 UTC, eunsucking commented on source/_posts/2017-10-31-release-v9.0.0.md
> +  * Error 이벤트를 두번 발생시키는 Request 버그가 수정되었습니다. [[`620ba41694`](https://github.com/nodejs/node/commit/620ba41694)] [#14659](https://github.com/nodejs/node/pull/14659)
두 번

2017-11-05 14:24 UTC, eunsucking commented on source/_posts/2017-10-31-release-v9.0.0.md
> +  * `setTimeout()`이 받는 timeout값이 부호없는 32비트 정수범위를 초과하는 경우 경고가 발생합니다. [[`ce3586da31`](https://github.com/nodejs/node/commit/ce3586da31)] [#15627](https://github.com/nodejs/node/pull/15627)
timeout 값이
부호 없는

2017-11-05 14:29 UTC, eunsucking commented
대부분의 파일에서 Notable Changes(H**HTTP/1**, *Timers**...)는 한번에 묶어서 주석처리 하고 있는것 같습니다.

2017-11-05 15:22 UTC, BaroqueCoding commented
꼼꼼히 봐주셔서 감사합니다!
전부 반영되었고 `* **Errors**`의 들여쓰기가 잘못되어 있던 부분도 수정했습니다.

2017-11-05 15:58 UTC, yous commented on source/_posts/2017-10-31-release-v9.0.0.md
> +  * Node.js 오류에 대한 정적 에러 코드 지정이 계속됩니다:
계속됩니다: → 계속됩니다.

2017-11-05 15:58 UTC, yous commented on source/_posts/2017-10-31-release-v9.0.0.md
> +  * `fs.ReadStream`와 `fs.WriteStream` 클래스들은 이제 `destroy()`를 사용합니다. [[`e5c290bed9`](https://github.com/nodejs/node/commit/e5c290bed9)] [#15407](https://github.com/nodejs/node/pull/15407)
\`fs.ReadStream\`와 → \`fs.ReadStream\`과

2017-11-05 15:58 UTC, yous commented on source/_posts/2017-10-31-release-v9.0.0.md
> +  * Error 이벤트를 두 번 발생시키는 Request 버그가 수정되었습니다. [[`620ba41694`](https://github.com/nodejs/node/commit/620ba41694)] [#14659](https://github.com/nodejs/node/pull/14659)
원문에는 \`'error'\`라고 되어 있는데, 이는 유지하는 게 좋을 것 같습니다.

Request \`'error'\` 이벤트를 두 번 발생시키는 버그가 수정되었습니다.

2017-11-05 15:58 UTC, yous commented on source/_posts/2017-10-31-release-v9.0.0.md
> +  * HTTP 클라이언트는 `net.Socket`를 통해 `Duplex`스트림을 범용적으로 사용할 수 있습니다. [[`3e25e4d00f`](https://github.com/nodejs/node/commit/3e25e4d00f)] [#16267](https://github.com/nodejs/node/pull/16267)
'HTTP 클라이언트는 \`net.Socket\`뿐만 아니라 범용 \`Duplex\` 스트림도 사용할 수 있습니다.'는 어떻습니까?

2017-11-05 16:08 UTC, BaroqueCoding commented on source/_posts/2017-10-31-release-v9.0.0.md
> +  * Node.js 오류에 대한 정적 에러 코드 지정이 계속됩니다:
원문에서는 이어지는 li 리스트에 앞서서 콜론 표시를 한 것 같은데 의미가 훼손되지는 않을까요?

2017-11-05 16:08 UTC, BaroqueCoding commented on source/_posts/2017-10-31-release-v9.0.0.md
> +  * `fs.ReadStream`와 `fs.WriteStream` 클래스들은 이제 `destroy()`를 사용합니다. [[`e5c290bed9`](https://github.com/nodejs/node/commit/e5c290bed9)] [#15407](https://github.com/nodejs/node/pull/15407)
반영하겠습니다

2017-11-05 16:14 UTC, BaroqueCoding commented on source/_posts/2017-10-31-release-v9.0.0.md
> +  * Error 이벤트를 두 번 발생시키는 Request 버그가 수정되었습니다. [[`620ba41694`](https://github.com/nodejs/node/commit/620ba41694)] [#14659](https://github.com/nodejs/node/pull/14659)
`error`는 유지하는게 맞는 것 같습니다.
문장은 그대로 유지하는게 전달력이 있다고 보는데 어떠신가요?

2017-11-05 16:26 UTC, BaroqueCoding commented on source/_posts/2017-10-31-release-v9.0.0.md
> +  * HTTP 클라이언트는 `net.Socket`를 통해 `Duplex`스트림을 범용적으로 사용할 수 있습니다. [[`3e25e4d00f`](https://github.com/nodejs/node/commit/3e25e4d00f)] [#16267](https://github.com/nodejs/node/pull/16267)
반영하겠습니다.

2017-11-05 19:10 UTC, yous commented on source/_posts/2017-10-31-release-v9.0.0.md
> +  * Node.js 오류에 대한 정적 에러 코드 지정이 계속됩니다:
한국어에서는 콜론을 문장 뒤에 사용하지 않습니다. 리스트가 한 단계 들여쓰기 되어 있으니 위에서 바로 이어지는 것이라고 이해할 수 있습니다. https://www.korean.go.kr/front/onlineQna/onlineQnaView.do?mn_id=60&qna_seq=122038&pageIndex=1

2017-11-05 19:18 UTC, yous commented on source/_posts/2017-10-31-release-v9.0.0.md
> +  * Error 이벤트를 두 번 발생시키는 Request 버그가 수정되었습니다. [[`620ba41694`](https://github.com/nodejs/node/commit/620ba41694)] [#14659](https://github.com/nodejs/node/pull/14659)
> A bug causing the request \`'error'\` event to fire twice was fixed.

여기에서 버그가 'the request \`'error'\` event'를 두 번 발생시킨다고 해석했는데, 리퀘스트가 에러 이벤트를 발생시키는 거라고 해석해야 할까요?

2017-11-05 23:23 UTC, BaroqueCoding commented on source/_posts/2017-10-31-release-v9.0.0.md
> +  * Error 이벤트를 두 번 발생시키는 Request 버그가 수정되었습니다. [[`620ba41694`](https://github.com/nodejs/node/commit/620ba41694)] [#14659](https://github.com/nodejs/node/pull/14659)
Request \`'error'\`는 표기 방식이 다른 두 단어가 붙어있는게 좀 모호하게 읽히는것 같아 그렇게 썼는데 괜찮으시다면 말씀하신대로 수정하겠습니다.

2017-11-05 23:43 UTC, BaroqueCoding commented on source/_posts/2017-10-31-release-v9.0.0.md
> +  * Node.js 오류에 대한 정적 에러 코드 지정이 계속됩니다:
설명 감사합니다. 반영하겠습니다

2017-11-06 02:27 UTC, yous commented on source/_posts/2017-10-31-release-v9.0.0.md
> +  * Error 이벤트를 두 번 발생시키는 Request 버그가 수정되었습니다. [[`620ba41694`](https://github.com/nodejs/node/commit/620ba41694)] [#14659](https://github.com/nodejs/node/pull/14659)
그러면 'Request의 \`'error'\` 이벤트'는 어떨까요?

2017-11-06 05:37 UTC, BaroqueCoding commented on source/_posts/2017-10-31-release-v9.0.0.md
> +  * Error 이벤트를 두 번 발생시키는 Request 버그가 수정되었습니다. [[`620ba41694`](https://github.com/nodejs/node/commit/620ba41694)] [#14659](https://github.com/nodejs/node/pull/14659)
따옴표를 겹쳐서 쓰는것도 이상할것 같고..
커밋을 다시 읽어보니 req.emit('error')를 수정하고 있는 것으로 봐서 request가 Eventemitter로 동작하는게 맞는 것 같은데 그대로
\`'error'\` 이벤트를 두 번 발생시키는 Request 버그가 수정되었습니다. 로 해도 될까요? 내용상으로 큰 차이는 없는것 같습니다.

2017-11-06 05:58 UTC, yous commented on source/_posts/2017-10-31-release-v9.0.0.md
> +  * Error 이벤트를 두 번 발생시키는 Request 버그가 수정되었습니다. [[`620ba41694`](https://github.com/nodejs/node/commit/620ba41694)] [#14659](https://github.com/nodejs/node/pull/14659)
아, ``Request `'error'` 이벤트`` 대신 ``Request의 `'error'` 이벤트``는 어떻냐는 이야기였습니다. 말씀하신 대로 고쳐도 별 문제 없을 것 같아요.

2017-11-06 08:01 UTC, BaroqueCoding commented on source/_posts/2017-10-31-release-v9.0.0.md
> +  * Error 이벤트를 두 번 발생시키는 Request 버그가 수정되었습니다. [[`620ba41694`](https://github.com/nodejs/node/commit/620ba41694)] [#14659](https://github.com/nodejs/node/pull/14659)
그렇다면
`'error'` 이벤트를 두 번 발생시키는 Request 버그가 수정되었습니다.
이것으로 확정하고 수정하겠습니다

2017-11-06 08:09 UTC, yous approved these changes

2017-11-06 13:19 UTC, eunsucking approved these changes

2017-11-06 14:57 UTC, merged