v11.1.0
nodejs/nodejs-ko pull request #768
Opened 2018-11-06 13:19 UTC by freenice12

close #767

2018-11-06 13:42 UTC, outsideris requested changes

2018-11-06 13:42 UTC, outsideris commented on source/_posts/2018-11-02-release-v11.1.0.md
> +  * Fixed an issue that could cause timers to enter an infinite loop. [#23870](https://github.com/nodejs/node/pull/23870)
번역이 되지 않았습니다.

2018-11-06 15:38 UTC, freenice12 commented on source/_posts/2018-11-02-release-v11.1.0.md
> +  * Fixed an issue that could cause timers to enter an infinite loop. [#23870](https://github.com/nodejs/node/pull/23870)
뭔가 잘못되었나봐요.;;
다시 커밋했습니다.

2018-11-06 15:38 UTC, freenice12 commented on source/_posts/2018-11-02-release-v11.1.0.md
> +  * Fixed an issue that could cause timers to enter an infinite loop. [#23870](https://github.com/nodejs/node/pull/23870)
확인 감사합니다!

2018-11-07 14:20 UTC, freenice12 reviewed
.

2018-11-07 14:22 UTC, yous approved these changes

2018-11-07 22:35 UTC, marocchino approved these changes

2018-11-08 12:45 UTC, outsideris approved these changes

2018-11-08 12:45 UTC, merged