Translate Node v12.8.1 (Current)
nodejs/nodejs-ko pull request #867
Opened 2019-08-23 02:18 UTC by marocchino

close #863

2019-08-23 02:20 UTC, marocchino commented on source/_posts/2019-08-15-release-v12.8.1.md
> +- **CVE-2019-9514 “Reset Flood”**: 공격자는 여러 스트림을 열고 각 스트림을 통해 잘못된 요청을 보내 피어에서 RST_STREAM 프레임의 스트림을 요청합니다. 피어가 RST_STREAM 프레임을 큐에 넣는 방법에 따라 메모리, CPU를 소비하게 하여 서비스 거부가 발생할 수 있습니다.
`RST\_STREAM`로 입력했는데 prettier가 RST_STREAM로 돌리는거보면 별문제 없는 모양입니다.

2019-08-23 02:25 UTC, yous commented on source/_posts/2019-08-15-release-v12.8.1.md
> +- **CVE-2019-9514 “Reset Flood”**: 공격자는 여러 스트림을 열고 각 스트림을 통해 잘못된 요청을 보내 피어에서 RST_STREAM 프레임의 스트림을 요청합니다. 피어가 RST_STREAM 프레임을 큐에 넣는 방법에 따라 메모리, CPU를 소비하게 하여 서비스 거부가 발생할 수 있습니다.
어떤 마크다운 엔진은 저런 식으로 가운데 하나만 있는 `_`는 알아서 무시하도록 되어 있더라고요. 일단 GFM이 그렇습니다. 빌드했을 때 문제없이 보이기만 하면 괜찮을 거 같네요.

2019-08-23 03:01 UTC, yous commented on source/_posts/2019-08-15-release-v12.8.1.md
> +보안 릴리즈 입니다.
```suggestion
보안 릴리즈입니다.
```

2019-08-23 03:01 UTC, yous commented on source/_posts/2019-08-15-release-v12.8.1.md
> +HTTP/2의 다른 구현체와 마찬가지로 Node.js에서 서비스 거부 공격을 할수 있는
```suggestion
HTTP/2의 다른 구현체와 마찬가지로 Node.js에서 서비스 거부 공격을 할 수 있는
```

2019-08-23 03:01 UTC, yous commented on source/_posts/2019-08-15-release-v12.8.1.md
> +- **CVE-2019-9511 “Data Dribble”**: 공격자는 특정 리소스에서 대량의 데이터를 여러 스트림으로 요청합니다. 윈도우 크기 및 스트림 우선 순위를 조작하여 서버가 1 바이트 청크로 데이터를 큐에 넣도록합니다. 이 데이터가 얼마나 효율적으로 큐에 넣는지에 따라 CPU, 메모리를 과도하게 소비하게 하여 서비스 거부가 발생할 수 있습니다
```suggestion
- **CVE-2019-9511 “Data Dribble”**: 공격자는 특정 리소스에서 대량의 데이터를 여러 스트림으로 요청합니다. 윈도우 크기 및 스트림 우선 순위를 조작하여 서버가 1 바이트 청크로 데이터를 큐에 넣도록 합니다. 이 데이터가 얼마나 효율적으로 큐에 넣는지에 따라 CPU, 메모리를 과도하게 소비하게 하여 서비스 거부가 발생할 수 있습니다.
```

2019-08-23 03:01 UTC, yous commented on source/_posts/2019-08-15-release-v12.8.1.md
> +- **CVE-2019-9512 “Ping Flood”**: 공격자는 지속적인 핑을 HTTP/2 피어로 보내 피어가 응답의 내부 큐를 작성하게합니다. 이 데이터가 얼마나 효율적으로 큐에 넣는지에 따라 CPU, 메모리를 과도하게 소비하게 하여 서비스 거부가 발생할 수 있습니다.
'응답의 내부 큐' 대신 '내부 응답 큐'는 어떤가요? 여러 요청에 대한 응답을 차례로 보내기 위한 큐인 것 같습니다.

```suggestion
- **CVE-2019-9512 “Ping Flood”**: 공격자는 지속적인 핑을 HTTP/2 피어로 보내 피어가 내부 응답 큐를 작성하게 합니다. 이 데이터가 얼마나 효율적으로 큐에 넣는지에 따라 CPU, 메모리를 과도하게 소비하게 하여 서비스 거부가 발생할 수 있습니다.
```

2019-08-23 03:01 UTC, yous commented on source/_posts/2019-08-15-release-v12.8.1.md
> +- **CVE-2019-9516 “0-Length Headers Leak”**: 공격자는 길이가 0 인 헤더 이름과 길이가 0 헤더 값을 가지는 헤더 스트림을 보냅니다. 추가로 이 해더는 Huffman이 1 바이트 이상으로 인코딩 될 수 있습니다. 일부 구현에서는 이러한 헤더에 메모리를 할당하고 세션이 종료 될 때까지 할당을 유지합니다. 이로 인해 불필요
```suggestion
- **CVE-2019-9516 “0-Length Headers Leak”**: 공격자는 길이가 0인 헤더 이름과 길이가 0인 헤더 값을 가지는 헤더 스트림을 보냅니다. 추가로 이 헤더의 허프만 인코딩 결과가 1 바이트 이상일 수 있습니다. 일부 구현에서는 이러한 헤더에 메모리를 할당하고 세션이 종료될 때까지 할당을 유지합니다. 이로 인해 불필요한 메모리가 소비되어 서비스 거부가 발생할 수 있습니다.
```

2019-08-23 03:01 UTC, yous commented on source/_posts/2019-08-15-release-v12.8.1.md
> +- **CVE-2019-9515 “Settings Flood”**: 공격자는 SETTINGS 프레임 스트림을 피어에게 보냅니다. RFC는 SETTINGS 프레임 당 하나의 승인으로 피어 응답을 요구하므로 빈 SETTINGS 프레임은 핑과 거의 동일하게 행동합니다. 이 데이터가 얼마나 효율적으로 큐에 넣는지에 따라 CPU, 메모리를 과도하게 소비하게 하여
https://www.korean.go.kr/front/onlineQna/onlineQnaView.do?mn_id=216&qna_seq=74643
```suggestion
- **CVE-2019-9515 “Settings Flood”**: 공격자는 SETTINGS 프레임 스트림을 피어에게 보냅니다. RFC는 SETTINGS 프레임당 하나의 승인으로 피어 응답을 요구하므로 빈 SETTINGS 프레임은 핑과 거의 동일하게 행동합니다. 이 데이터가 얼마나 효율적으로 큐에 넣는지에 따라 CPU, 메모리를 과도하게 소비하게 하여 서비스 거부가 발생할 수 있습니다.
```

2019-08-23 03:01 UTC, yous commented on source/_posts/2019-08-15-release-v12.8.1.md
> +- **CVE-2019-9517 “Internal Data Buffering”**: 공격자는 HTTP/2 윈도우를 열어서 피어가 제약없이 전송할 수 있지만, TCP 윈도우를 닫은 상태에서 피어가 실제로 (많은) 바이트를 쓸 수는 없습니다. 이 상태에서 공격자는 큰 응답 개체에 대한 요청 스트림을 보냅니다. 서버가 응답을 큐에 넣는 방법에 따라 메모리, C
```suggestion
- **CVE-2019-9517 “Internal Data Buffering”**: 공격자는 HTTP/2 윈도우를 열어서 피어가 제약 없이 전송할 수 있지만, TCP 윈도우를 닫아 놓기 때문에 피어가 실제로 (많은) 바이트를 쓸 수는 없습니다. 이 상태에서 공격자는 큰 응답 개체에 대한 요청 스트림을 보냅니다. 서버가 응답을 큐에 넣는 방법에 따라 메모리, CPU를 과도하게 소비하여 서비스 거부가 발생할 수 있습니다.
```

2019-08-23 03:01 UTC, yous commented on source/_posts/2019-08-15-release-v12.8.1.md
> +- **CVE-2019-9518 “Empty Frames Flood”**: 공격자는 end-of-stream 플래그없이 빈 페이로드 프레임 스트림을 보냅니다. 이 프레임은 DATA, HEADERS, CONTINUATION, PUSH_PROMISE일 수 있습니다. 피어는 각 프레임을 처리하는 데 시간을 소비하여 대역폭을 공격합니다. 이로 인해 과도한 CPU
```suggestion
- **CVE-2019-9518 “Empty Frames Flood”**: 공격자는 end-of-stream 플래그 없이 빈 페이로드 프레임 스트림을 보냅니다. 이 프레임은 DATA, HEADERS, CONTINUATION, PUSH_PROMISE일 수 있습니다. 피어는 각 프레임을 처리하는 데 시간을 소비하여 대역폭을 공격합니다. 이로 인해 과도한 CPU가 소비되어 서비스 거부가 발생할 수 있습니다.(구글의 Piotr Sikora가 발견)
```

2019-08-23 03:13 UTC, yous approved these changes

2019-08-27 14:40 UTC, Fleta requested changes

2019-08-27 14:40 UTC, Fleta commented on source/_posts/2019-08-15-release-v12.8.1.md
> +보안 릴리즈입니다.
```suggestion
보안 릴리스입니다.
```

2019-08-28 01:55 UTC, marocchino commented on source/_posts/2019-08-15-release-v12.8.1.md
> +보안 릴리즈입니다.
65d6358

2019-08-28 13:06 UTC, Fleta approved these changes

2019-08-28 23:31 UTC, merged