Translate v12.9.0, v12.9.1 and v12.10.0
nodejs/nodejs-ko pull request #888
Opened 2019-10-24 06:16 UTC by outsideris

close #866
close #871 
close #872

2019-10-24 22:10 UTC, marocchino requested changes

2019-10-24 22:10 UTC, marocchino commented on source/_posts/2019-09-04-release-v12.10.0.md
> +  * \*timeNs properties to BigInt Stats 객체에 \*timeNs 속성을 추가했습니다. (Joyee Cheung) [#21387](https://github.com/nodejs/node/pull/21387)
```suggestion
  * BigInt Stats 객체에 \*timeNs 속성을 추가했습니다. (Joyee Cheung) [#21387](https://github.com/nodejs/node/pull/21387)
```

2019-10-24 22:10 UTC, marocchino commented on source/_posts/2019-08-20-release-v12.9.0.md
> +  * (프로미스 버전) `fs.writev`, `fs.writevSync`, `filehandle.writev` 메서드를 추가했습니다. 이 메서드로 파일 디스크립터에 `ArrayBufferView`의 배열을 작성할 수 있습니다. (Anas Aboureada) [#25925](https://github.com/nodejs/node/pull/25925),
커밋읽어봤는데 프로미스 버전은 `filehandle.writev`에만 해당되는것 같습니다.
```suggestion
  * `fs.writev`, `fs.writevSync`, `filehandle.writev` (프로미스 버전) 메서드를 추가했습니다. 이 메서드로 파일 디스크립터에 `ArrayBufferView`의 배열을 작성할 수 있습니다. (Anas Aboureada) [#25925](https://github.com/nodejs/node/pull/25925), (cjihrig) [#29186](https://github.com/nodejs/node/pull/29186).
```

2019-10-25 05:54 UTC, yous commented on source/_posts/2019-08-20-release-v12.9.0.md
> +  * `OutgoingMessage.prototype`에 세 가지 파라미터 `writableObjectMode`, `writableLength`, `writableHighWaterMark`를 추가했습니다. [#29018](https://github.com/nodejs/node/pull/29018).
```suggestion
  * `OutgoingMessage.prototype`에 세 가지 속성 `writableObjectMode`, `writableLength`, `writableHighWaterMark`를 추가했습니다. [#29018](https://github.com/nodejs/node/pull/29018).
```

2019-10-25 05:54 UTC, yous commented on source/_posts/2019-08-26-release-v12.9.1.md
> +이번 릴리스는 **http** 모듈의 두가지 회귀 문제를 수정합니다.
```suggestion
이번 릴리스는 **http** 모듈의 두 가지 회귀 문제를 수정합니다.
```

2019-10-28 08:46 UTC, taggon commented on source/_posts/2019-08-20-release-v12.9.0.md
> +  * 읽을 수 있는 스트림에 새로운 `readableEnded` 속성을 추가했습니다. `'end'` 이벤트가 발생했을 때 이 값이 `true`로 설정됩니다. (Robert Nagy) [#28814](https://github.com/nodejs/node/pull/28814).
"새로운 xxx 속성을 추가했다"를 "xxx 속성을 새로 추가했다"고 바꾸는 건 어떨까요? 그게 읽기에 더 자연스러운 것 같습니다.

2019-11-02 06:06 UTC, outsideris commented
수정했습니다.

2019-11-02 06:06 UTC, yous approved these changes

2019-11-02 13:55 UTC, marocchino approved these changes

2019-11-02 13:56 UTC, merged