translate v13.0.0
nodejs/nodejs-ko pull request #891
Opened 2019-10-27 10:26 UTC by Fleta

close #886

`assertion error`는 이전의 문서를 참고하려 `단언문 오류`로 번역했습니다.
`edge case` 같은 경우 `경계 조건` 으로 번역해보려고 했는데, `corner case` 와 헷갈릴 것 같아서.. 일단 한글로 `엣지 케이스` 라고 번역했습니다.

2019-10-28 01:46 UTC, yous commented on source/_posts/2019-10-22-release-v13.0.0.md
> +  * `assert.throws()` 또는 `assert.reject()`에서 발생한 오류 인스턴스의 유효성을 검사하기 위해 생성자 함수가 전달되면 원래 오류 대신 단언문 오류가 발생합니다. (Ruben Bridgewater) [#28263](https://github.com/nodejs/node/pull/28263).
PR을 보면 `assert.rejects()`가 맞는 것 같습니다.
```suggestion
  * `assert.throws()` 또는 `assert.rejects()`에서 발생한 오류 인스턴스의 유효성을 검사하기 위해 생성자 함수가 전달되면 원래 오류 대신 단언문 오류가 발생합니다. (Ruben Bridgewater) [#28263](https://github.com/nodejs/node/pull/28263).
```

2019-10-28 01:46 UTC, yous commented on source/_posts/2019-10-22-release-v13.0.0.md
> +  * 중단된 요청은 이제 `aborted` 된 후에 `end` 또는 `error` 이벤트를 생성하지 않습니다.
`aborted`도 이벤트인 것 같으니 이렇게 쓰는 건 어떨까요?
```suggestion
  * 중단된 요청은 이제 `aborted` 이벤트 후에 `end` 또는 `error` 이벤트를 생성하지 않습니다.
```

2019-10-28 01:46 UTC, yous commented on source/_posts/2019-10-22-release-v13.0.0.md
> +  * HTTP 요청에 대한 `host` 옵션은 이제 문자열 값으로 확인됩니다. (Giorgos Ntemiris) [#29568](https://github.com/nodejs/node/pull/29568).
`host` 옵션이 문자열인지 검사한다는 얘기 같습니다.
```suggestion
  * HTTP 요청에 대한 `host` 옵션은 이제 문자열 값인지 검증됩니다. (Giorgos Ntemiris) [#29568](https://github.com/nodejs/node/pull/29568).
```

2019-10-28 01:46 UTC, yous commented on source/_posts/2019-10-22-release-v13.0.0.md
> +  * `process.env.TZ`의 값을 변경하면 TZ 캐시가 삭제됩니다. 이는 `Data.prototype.toString`등의 메서드가 사용하는 기본 시간대에 영향을 줍니다. (Ben Noordhuis) [#20026](https://github.com/nodejs/node/pull/20026).
```suggestion
  * `process.env.TZ`의 값을 변경하면 TZ 캐시가 삭제됩니다. 이는 `Data.prototype.toString` 등의 메서드가 사용하는 기본 시간대에 영향을 줍니다. (Ben Noordhuis) [#20026](https://github.com/nodejs/node/pull/20026).
```

2019-10-28 01:57 UTC, Fleta commented on source/_posts/2019-10-22-release-v13.0.0.md
> +  * `process.env.TZ`의 값을 변경하면 TZ 캐시가 삭제됩니다. 이는 `Data.prototype.toString`등의 메서드가 사용하는 기본 시간대에 영향을 줍니다. (Ben Noordhuis) [#20026](https://github.com/nodejs/node/pull/20026).
이거는 `Data.prototype.toString` 외의 다른 메서드도 있다는 의미를 가지는 의존명사라 띄어쓰는게 맞는 것 같습니다

2019-10-28 08:44 UTC, taggon requested changes
수정할 부분 몇 가지를 코멘트 남겼습니다. 특히 deprecation에 관한 오류가 눈에 띄는데 deprecated 됐다는 말은 후속 릴리스에서 폐기할 예정으로 표시해둔다는 의미이지 당장 사용할 수 없다는 의미가 아닙니다.

2019-10-28 08:44 UTC, taggon commented on source/_posts/2019-10-22-release-v13.0.0.md
> +  * `request.connection` 및 `response.connection` 속성이 런타임 폐기되었습니다. 대신 이와 동등한 `request.socket`과 `response.socket`을 사용해야 합니다. (Robert Nagy) [#29015](https://github.com/nodejs/node/pull/29015).
`deprecated`는 `폐기 예정`이지 폐기 되었다는 뜻이 아닙니다.
참고 https://github.com/nodejs/nodejs-ko/blob/3efe2716e48395f0563747bddd3727f401d063da/source/_posts/2018-09-06-release-v10.10.0.md

2019-10-28 08:44 UTC, taggon commented on source/_posts/2019-10-22-release-v13.0.0.md
> +  * `module.createRequireFromPath()`는 폐기되었습니다. `module.createRequire()`를 대신 사용하세요. (cjihrig) [#27951](https://github.com/nodejs/node/pull/27951).
`deprecated` 오역 수정 필요합니다.

2019-10-28 08:44 UTC, taggon commented on source/_posts/2019-10-22-release-v13.0.0.md
> +  * `assert.throws()` 또는 `assert.rejects()`에 전달 된 유효성 검사 함수가 `true` 이외의 값을 반환하면 프로그래밍이 잘못되었음을 강조하기 위하여 원래의 오류 대신 단언문 오류가 발생합니다. (Ruben Bridgewater) [#28263](https://github.com/nodejs/node/pull/28263)
* 전달 된 -> 전달된 (띄어쓰기)
* "프로그래밍이 잘못되었음을 강조하기 위하여" 보다는 "프로그래밍 상의 실수를 강조하기 위해"로 고치는 건 어떤가요?

2019-10-28 08:44 UTC, taggon commented on source/_posts/2019-10-22-release-v13.0.0.md
> +  * `ChildProcess._channel`(DEP0129)이 런타임 폐기되었습니다. (cjihrig) [#27949](https://github.com/nodejs/node/pull/27949).
deprecation은 폐기가 아닌 폐기 예정입니다.

2019-10-28 14:20 UTC, Fleta commented on source/_posts/2019-10-22-release-v13.0.0.md
> +  * `request.connection` 및 `response.connection` 속성이 런타임 폐기되었습니다. 대신 이와 동등한 `request.socket`과 `response.socket`을 사용해야 합니다. (Robert Nagy) [#29015](https://github.com/nodejs/node/pull/29015).
runtime deprecation이 과거에 어떻게 번역되었는지 보다가 `~emit a runtime deprecation warning` 을 `~런타임 폐기 경고를 발생시킨다` 라고 번역한 걸 보게 되어서 순간 제가 착각한 것 같습니다. 지적해주셔서 감사하고 [c2d69da](https://github.com/nodejs/nodejs-ko/pull/891/commits/c2d69daf6e65971f9b2f1fc75e460b6f8aa7f2f9) 에서 전부 수정했습니다.

2019-10-28 14:20 UTC, Fleta commented on source/_posts/2019-10-22-release-v13.0.0.md
> +  * `process.env.TZ`의 값을 변경하면 TZ 캐시가 삭제됩니다. 이는 `Data.prototype.toString`등의 메서드가 사용하는 기본 시간대에 영향을 줍니다. (Ben Noordhuis) [#20026](https://github.com/nodejs/node/pull/20026).
다른 분의 특별한 의견이 없어 resolve 처리 합니다

2019-10-28 15:44 UTC, yous commented on source/_posts/2019-10-22-release-v13.0.0.md
> +  * `process.env.TZ`의 값을 변경하면 TZ 캐시가 삭제됩니다. 이는 `Data.prototype.toString`등의 메서드가 사용하는 기본 시간대에 영향을 줍니다. (Ben Noordhuis) [#20026](https://github.com/nodejs/node/pull/20026).
음... 띄어쓰는 게 맞으면 적용한다는 얘기신가요?

의존명사 '등'과 접미사 '-들'에 관한 링크입니다. https://www.korean.go.kr/front/mcfaq/mcfaqView.do?mn_id=62&mcfaq_seq=540&pageIndex=449

2019-10-28 16:48 UTC, Fleta commented on source/_posts/2019-10-22-release-v13.0.0.md
> +  * `process.env.TZ`의 값을 변경하면 TZ 캐시가 삭제됩니다. 이는 `Data.prototype.toString`등의 메서드가 사용하는 기본 시간대에 영향을 줍니다. (Ben Noordhuis) [#20026](https://github.com/nodejs/node/pull/20026).
아.. 띄어써야한다고 생각했던 부분인데 반대였네요.. 띄어쓰기를 안 한 채로 커밋을 했을 줄이야.. 정신리스해서 죄송하구 늦은 밤중에 고생 많으십니다 ㅜㅜ

2019-10-28 17:06 UTC, yous commented on source/_posts/2019-10-22-release-v13.0.0.md
> +  * `process.env.TZ`의 값을 변경하면 TZ 캐시가 삭제됩니다. 이는 `Data.prototype.toString`등의 메서드가 사용하는 기본 시간대에 영향을 줍니다. (Ben Noordhuis) [#20026](https://github.com/nodejs/node/pull/20026).
아닙니다. 😄 항상 번역해주셔서 감사합니다!

2019-10-28 23:25 UTC, marocchino approved these changes

2019-10-31 09:01 UTC, taggon approved these changes

2019-10-31 09:03 UTC, merged